<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4FwMMO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4FwMMO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA4FwMMO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA4FwMMO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA4FwMMO\App_KernelDevDebugContainer([
    'container.build_hash' => 'A4FwMMO',
    'container.build_id' => '92513ea5',
    'container.build_time' => 1644702131,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4FwMMO');
